name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
env:
  DOCKER_IMAGE_NAME: key-keeper
jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Test and Build
        run: |
          sbt -v +test
          sbt -v assembly
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: key-keeper-jar
          path: target/scala-2.13/key-keeper.jar
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: key-keeper-jar
          path: target/scala-2.13
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set GIT_TAG environment variable
        run: echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:${{ env.GIT_TAG }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:${{ env.GIT_TAG }}
      - name: Remove the local image
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
          docker rmi ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:${{ env.GIT_TAG }}
